parameters:
    itm.storage.filesystem_name: itm

services:
    itm.storage:
        class: ITM\StorageBundle\Util\StorageManipulator
        arguments:
            - @knp_gaufrette.filesystem_map
            - @doctrine
            - %itm.storage.filesystem_name%
            - @event_dispatcher

    itm.storage.api_key_user_provider:
        class: ITM\StorageBundle\Security\APIKeyUserProvider
        arguments:
            - @doctrine

    itm.storage.api_key_authenticator:
        class:  ITM\StorageBundle\Security\APIKeyAuthenticator
        public: false

    itm.storage.event_listener.document:
        class: ITM\StorageBundle\EventListener\DocumentEventListener
        arguments:
            - @gearman
        tags:
            - {name: kernel.event_listener, event: itm.storage.document.add, method: onDocumentAdd}
            - {name: kernel.event_listener, event: itm.storage.document.delete, method: onDocumentDelete}
            - {name: kernel.event_listener, event: itm.storage.document.restore, method: onDocumentRestore}
