parameters:
    itm.storage.filesystem_name: itm

services:
    itm.storage:
        class:      ITM\StorageBundle\Util\StorageManipulator
        arguments:
            - @knp_gaufrette.filesystem_map
            - @doctrine
            - %itm.storage.filesystem_name%